version: "3.3"

services:
    app:
        restart: always
        build: .
        container_name: expressjs
        volumes: 
            - .:/app
        ports:
            - '80:3000'
        command: ["npm", "start"]