services:
  app:
    restart: always
    container_name: marccent_client
    build: .
    volumes: 
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '0.0.0.0:3000:3000'
    # command: npm run dev