version: "3.7"

services:
    app:
        restart: always
        container_name: marccent_server
        build: .
        volumes: 
            - .:/app
        ports:
            - '8000:8000'
        command: gunicorn server.wsgi:application --bind 0.0.0.0:8000 --workers 3