version: '3.7'

services:
  strapi:
    image: strapi/strapi
    container_name: strapi
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: 138.128.247.222
      DATABASE_PORT: 3306
      DATABASE_NAME: marccent
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: S!WJNhQIJcnWFP1rD0AknhNT
      DATABASE_SSL: 'false'
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'